branch-defaults:
  feature:
    environment: eb-image-gallery-test-dev
    group_suffix: null
global:
  application_name: '"image-gallery-test"'
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker 18.06.1-ce
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
