version: '2'

services:
  image-gallery-service:
    container_name: image-gallery-service
    restart: always
    build: .
    links:
      - mongo
  mongo:
    container_name: mongo
    volumes: 
    - /Users/MyFolder/mongodb-data
    image: mongo:latest
    ports: 
      - '27017:27017'

   
