version: "2"
services:
  lodge:
    container_name: lodge
    build: 
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongo_server
      - MONGO_INITDB_ROOT_USERNAME=mfrenkel
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - PORT=3000
    depends_on:
      - 'database'
    links: 
      - database:mongo_server
  database:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
