version: "3"
services:
  app:
    container_name: lodge
    restart: always
    build: ./
    depends_on:
      - 'mongodb'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    entrypoint: ['npm', 'start']
  mongodb:
    restart: always 
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    